# Generated by Django 4.2.4 on 2023-08-28 02:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"employees_data"."departments"',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"employees_data"."jobs"',
            },
        ),
        migrations.CreateModel(
            name='HiredEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcc_historic_data_db.department')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcc_historic_data_db.job')),
            ],
            options={
                'db_table': '"employees_data"."hired_employees"',
            },
        ),
    ]
